apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterissuer }}
  creationTimestamp: null
  labels:
    io.kompose.service: deluge
  name: deluge
spec:
  rules:
  - host: deluge.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: deluge
          servicePort: 8112
  tls:
  - hosts:
    - deluge.{{ .Values.domain_name }}
    secretName: deluge-crt
status:
  loadBalancer: {}
