apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: emby.{{ .Values.domain_name }}
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: emby
  name: emby
spec:
  ports:
  - name: "8096"
    port: 8096
    targetPort: 8096
  - name: "8920"
    port: 8920
    targetPort: 8920
  selector:
    io.kompose.service: emby
status:
  loadBalancer: {}
