apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: emby
  name: emby
spec:
  rules:
  - host: emby.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: emby
          servicePort: 8096
status:
  loadBalancer: {}
