apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: headphones
  name: headphones
spec:
  rules:
  - host: headphones.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: headphones
          servicePort: 8181
status:
  loadBalancer: {}
