apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: headphones.{{ .Values.domain_name }}
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: headphones
  name: headphones
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: headphones
    spec:
      containers:
      - env:
        - name: TZ
          value: '{{ .Values.timezone}}'
        image: linuxserver/headphones
        name: headphones
        ports:
        - containerPort: 8181
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: headphones-config
      restartPolicy: Always
      volumes:
      - name: headphones-config
        hostPath:
          path: /opt/headphones/config
status: {}
