apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterissuer }}
  creationTimestamp: null
  labels:
    io.kompose.service: heimdall
  name: heimdall
spec:
  rules:
  - host: heimdall.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: heimdall
          servicePort: 80
  tls:
  - hosts:
    - heimdall.{{ .Values.domain_name }}
    secretName: heimdall-crt
status:
  loadBalancer: {}
