apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: heimdall.{{ .Values.domain_name }}
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: heimdall
  name: heimdall
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: heimdall
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: '{{ .Values.timezone }}'
        image: linuxserver/heimdall
        name: heimdall
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: heimdall-config
        - mountPath: /var/www/localhost/heimdall/.env
          name: heimdall-env
      restartPolicy: Always
      volumes:
      - name: heimdall-config
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
            path: /seedbox/heimdall/config
      - name: heimdall-env
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
            path: /seedbox/heimdall/var/www/localhost/heimdall/.env
status: {}
