apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: myingressauthsecret
    ingress.kubernetes.io/auth-realm: "Authentication Required - foo"
  creationTimestamp: null
  labels:
    io.kompose.service: heimdall
  name: heimdall
spec:
  rules:
  - host: heimdall.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: heimdall
          servicePort: 80
status:
  loadBalancer: {}
