apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: netdata.{{ .Values.domain_name }}
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: netdata
  name: netdata
spec:
  ports:
  - name: "19999"
    port: 19999
    targetPort: 19999
  selector:
    io.kompose.service: netdata
status:
  loadBalancer: {}
