apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: netdata-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Netdata Authentication Required - netdata"
  creationTimestamp: null
  labels:
    io.kompose.service: netdata
  name: netdata
spec:
  rules:
  - host: netdata.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: netdata
          servicePort: 19999
status:
  loadBalancer: {}
