apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: plex.daydreamnation.fr
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: plex
    spec:
      containers:
      - env:
        - name: ADVERTISE_IP
          value: '"http://10.1.1.23:32400/"'
        - name: TZ
          value: Europe/Paris
        image: plexinc/pms-docker
        name: plex
        ports:
        - containerPort: 32400
        - containerPort: 3005
        - containerPort: 8324
        - containerPort: 32469
        - containerPort: 1900
          protocol: UDP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: plex-config
        - mountPath: /transcode \
          name: plex-transcode
        - mountPath: /data/tv
          name: deluge-data-tv
        - mountPath: /data/movies
          name: deluge-data-movies
      restartPolicy: Always
      volumes:
      - name: plex-config
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
      - name: plex-transcode
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
      - name: deluge-data-tv
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
      - name: deluge-data-movies
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
status: {}
