apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterissuer }}
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  rules:
  - host: radarr.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: radarr
          servicePort: 7878
  tls:
  - hosts:
    - radarr.{{ .Values.domain_name }}
    secretName: radarr-crt
status:
  loadBalancer: {}
