apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  rules:
  - host: radarr.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: radarr
          servicePort: 7878
status:
  loadBalancer: {}
