apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: radarr.{{ .Values.domain_name }}
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: radarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1000"
        - name: TZ
          value: '{{ .Values.timezone}}'
        image: linuxserver/radarr
        name: radarr
        ports:
        - containerPort: 7878
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: radarr-config
      restartPolicy: Always
      volumes:
      - name: radarr-config
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: myfs
            clusterNamespace: rook-ceph
            path: /seedbox/radarr/config
status: {}
