apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterissuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  creationTimestamp: null
  labels:
    io.kompose.service: seafile
  name: seafile
spec:
  rules:
  - host: seafile.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: seafile
          servicePort: 80
  tls:
  - hosts:
    - seafile.{{ .Values.domain_name }}
    secretName: seafile-crt
status:
  loadBalancer: {}
