apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: sonarr.{{ .Values.domain_name }}
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: sonarr
status:
  loadBalancer: {}
